#######################################################################################
# Book settings
title : PSSP Virtual Notebook
author: Matteo Salvalaglio
copyright                   : "2021"  # Copyright year to be placed in the footer
logo: 'Logo.png'

# Information about where the book exists on the web
description: >-
  A virtual notebook for "CENG0011: Particulate Systems and Separation Processes II @ UCL Chemical Engineering."

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false
  
# Information about where the book exists on the web
repository:
  url                       : https://msalvalaglio.github.io/PSSP_notebook/index.html

repository:
  url: https://github.com/msalvalaglio/PSSP_notebook

html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button     : true
  path_to_book: https://github.com/msalvalaglio/PSSP_notebook  # An optional path to your book, defaults to repo root
  
  launch_buttons: off
  binderhub_url: off
  
# #######################################################################################
# Interact link settings
#notebook_interface            : "notebook"

#parse:
 # myst_enable_extensions:
  #  - amsmath
